baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Fernando Rodriguez"
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

## Make an about page and a CV page
[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/Fernando-Rz"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"