baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Fernando Rodriguez"
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
    footer = "Fernando Rodriguez"
    avatarURL = "/images/portfolio-picture.jpg"
    description = "Software Engineer · North Carolina"
    socialIcons = [
        {name= "linkedin", url = "https://www.linkedin.com/in/fernando-rodriguez-barranca/"},
        {name= "github", url = "https://github.com/Fernando-Rz"},
        {name= "email", url = "mailto:fernando.rodriguezb2@gmail.com"},
    ]

## Make an about page and a CV page
[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "about"

    url = "/about/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "About"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "resume"
    weight = 2
    
